[project]
name = "agent-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.2",
    "pydantic-ai>=0.0.52",
    "ruff>=0.11.4",
]
